# try or catch sy exception handling hoti hy python ma 


try :
    a = int(input("Enter a number : "))
    print(f'The square of {a} is : {a*a}')
except Exception as e :
    print(e) # idht e ki jagha apni marzi ka koi msg bhi likh skty hain

print("some important lines of code .")
print("End of code .")